FROM quay.io/eris/base:alpine
MAINTAINER Monax <support@monax.io>

ENV TARGET eris-pm

# Get the binary from the artifact in pwd
COPY ./"$TARGET"_build_artifact $INSTALL_BASE/$TARGET
RUN chmod +x $INSTALL_BASE/$TARGET

# Finalize
RUN chown --recursive $USER:$USER /home/$USER
VOLUME $ERIS
WORKDIR $ERIS
USER $USER
ENTRYPOINT eris-pm
