package main

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/eris-ltd/eris-cli/commands"

	. "github.com/eris-ltd/eris-cli/Godeps/_workspace/src/github.com/spf13/cobra"
)

func printOptions(out *bytes.Buffer, cmd *Command, name string) {
	flags := cmd.NonInheritedFlags()
	flags.SetOutput(out)
	if flags.HasFlags() {
		fmt.Fprintf(out, "### Options\n\n```\n")
		flags.PrintDefaults()
		fmt.Fprintf(out, "```\n\n")
	}

	parentFlags := cmd.InheritedFlags()
	parentFlags.SetOutput(out)
	if parentFlags.HasFlags() {
		fmt.Fprintf(out, "### Options inherited from parent commands\n\n```\n")
		parentFlags.PrintDefaults()
		fmt.Fprintf(out, "```\n\n")
	}
}

type byName []*Command

func (s byName) Len() int           { return len(s) }
func (s byName) Swap(i, j int)      { s[i], s[j] = s[j], s[i] }
func (s byName) Less(i, j int) bool { return s[i].Name() < s[j].Name() }

func MyGenMarkdown(cmd *Command, out *bytes.Buffer) {
	MyGenMarkdownCustom(cmd, out, func(s string) string { return s })
}

func MyGenMarkdownCustom(cmd *Command, out *bytes.Buffer, linkHandler func(string) string) {
	name := cmd.CommandPath()

	short := cmd.Short
	long := cmd.Long
	if len(long) == 0 {
		long = short
	}

	fmt.Fprintf(out, "## %s\n\n", name)
	fmt.Fprintf(out, "%s\n\n", short)
	fmt.Fprintf(out, "### Synopsis\n\n")
	fmt.Fprintf(out, "\n%s\n\n", long)

	if cmd.Runnable() {
		fmt.Fprintf(out, "```\n%s\n```\n\n", cmd.UseLine())
	}

	if len(cmd.Example) > 0 {
		fmt.Fprintf(out, "### Examples\n\n")
		fmt.Fprintf(out, "```\n%s\n```\n\n", cmd.Example)
	}

	printOptions(out, cmd, name)

	if len(cmd.Commands()) > 0 || cmd.HasParent() {
		fmt.Fprintf(out, "### SEE ALSO\n")
		if cmd.HasParent() {
			parent := cmd.Parent()
			pname := parent.CommandPath()
			link := pname + ".md"
			link = strings.Replace(link, " ", "_", -1)
			fmt.Fprintf(out, "* [%s](%s)\t - %s\n", pname, linkHandler(link), parent.Short)
		}

		children := cmd.Commands()
		sort.Sort(byName(children))

		for _, child := range children {
			if len(child.Deprecated) > 0 {
				continue
			}
			cname := name + " " + child.Name()
			link := cname + ".md"
			link = strings.Replace(link, " ", "_", -1)
			fmt.Fprintf(out, "* [%s](%s)\t - %s\n", cname, linkHandler(link), child.Short)
		}
		fmt.Fprintf(out, "\n")
	}

	// fmt.Fprintf(out, "###### Auto generated by spf13/cobra at %s\n", time.Now().UTC())
}

func MyGenMarkdownTree(cmd *Command, dir string) {
	identity := func(s string) string { return s }
	emptyStr := func(s string) string { return "" }
	MyGenMarkdownTreeCustom(cmd, dir, emptyStr, identity)
}

func MyGenMarkdownTreeCustom(cmd *Command, dir string, filePrepender func(string) string, linkHandler func(string) string) {
	for _, c := range cmd.Commands() {
		MyGenMarkdownTreeCustom(c, dir, filePrepender, linkHandler)
	}
	out := new(bytes.Buffer)

	MyGenMarkdownCustom(cmd, out, linkHandler)

	filename := cmd.CommandPath()
	filename = dir + strings.Replace(filename, " ", "_", -1) + ".md"
	outFile, err := os.Create(filename)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	defer outFile.Close()
	_, err = outFile.WriteString(filePrepender(filename))
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	_, err = outFile.Write(out.Bytes())
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func main() {
	eris := commands.ErisCmd
	commands.AddCommands()

	MyGenMarkdownTree(eris, "./eris-cli/")

	// out := new(bytes.Buffer)
	// cobra.MyGenMarkdown(eris, out)
	// _, _ = out.WriteString("\n\n")
	// cobra.MyGenMarkdown(commands.Projects, out)
	// _, _ = out.WriteString("\n\n")
	// cobra.MyGenMarkdown(commands.Chains, out)
	// _, _ = out.WriteString("\n\n")
	// cobra.MyGenMarkdown(commands.Services, out)
	// _, _ = out.WriteString("\n\n")
	// cobra.MyGenMarkdown(commands.Actions, out)
	// _, _ = out.WriteString("\n\n")
	// cobra.MyGenMarkdown(commands.Remotes, out)
	// _, _ = out.WriteString("\n\n")
	// cobra.MyGenMarkdown(commands.Keys, out)
	// _, _ = out.WriteString("\n\n")
	// cobra.MyGenMarkdown(commands.Config, out)
	// _, _ = out.WriteString("\n\n")
	// cobra.MyGenMarkdown(commands.Version, out)

	// outFile, err := os.Create("./eris.md")
	// if err != nil {
	//   fmt.Println(err)
	//   os.Exit(1)
	// }
	// defer outFile.Close()

	// _, err = outFile.Write(out.Bytes())
	// if err != nil {
	//   fmt.Println(err)
	//   os.Exit(1)
	// }
}
